### ISSUE TITLE
Chapter 5 scripts: no load_pdbbind() attribute in version 2.1.0 of deepchem with python2.7

### ISSUE THREAD

**Issue by MooersLab** [deepchem/DeepLearningLifeSciences#5]
The two sample scripts for chapter 5 are not working with deepchem version 2.1.0 running with python2.7 on a Mac Mojave. 

Traceback (most recent call last):
  File "./pdbbind_nn.py", line 5, in <module>
    pdbbind_tasks, pdbbind_datasets, transformers = dc.molnet.load_pdbbind(featurizer="grid", split="random", subset="core")
AttributeError: 'module' object has no attribute 'load_pdbbind'

I get the same error with the other file.
There is an attribute load_pdbbind_grid().

>>> pdbbind_tasks, pdbbind_datasets, transformers = dc.molnet.load_pdbbind_grid(split='random', featurizer='grid', subset='core', reload=True)
Loading dataset from disk.
TIMING: dataset construction took 0.031 s
Loading dataset from disk.
TIMING: dataset construction took 0.191 s
Loading dataset from disk.
TIMING: dataset construction took 0.022 s
Loading dataset from disk.
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: 'NoneType' object is not iterable

I am stuck.

**Comment by rbharath** [comment]
Could you upgrade to DeepChem 2.2? The book scripts are intended to be run with 2.2 and later versions of DeepChem.

**Comment by bmooers** [comment]
Thank you for the suggestion.

After removing macports from my path, I was able to install deepchem with python3.5 from source after running the bash script. The code in question is now starting to download a 2GB file.

Please note that the version number in deepchem/__init__.py in GitHub is 2.1.1. when maybe it should be 2.2.1.

**Comment by bmooers** [comment]
You can close this issue.
